CREATE TABLE `goods` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(256) NOT NULL,
  `category_id` varchar(256) DEFAULT NULL,
  `promotion` varchar(256) DEFAULT NULL,
  `keyword` varchar(256) DEFAULT NULL,
  `unit` varchar(45) DEFAULT NULL,
  `tags` varchar(256) DEFAULT NULL,
  `brand_id` int(11) DEFAULT NULL,
  `supplier_id` int(11) DEFAULT NULL,
  `base_sale` int(11) DEFAULT NULL COMMENT '基础销售数\n',
  `base_click` int(11) DEFAULT NULL COMMENT '基础点击数',
  `base_share` int(11) DEFAULT NULL COMMENT '基础分享数\n',
  `product_code` varchar(128) DEFAULT NULL,
  `starttime` date DEFAULT NULL COMMENT '生产日期\n',
  `validity_period` int(11) DEFAULT NULL COMMENT '保质周期 天数\n',
  `inventory` int(11) DEFAULT NULL COMMENT '库存',
  `inventory_warn` int(11) DEFAULT NULL COMMENT '库存预警',
  `place` varchar(256) DEFAULT NULL,
  `sku_ids` varchar(512) DEFAULT NULL,
  `photo` varchar(256) DEFAULT NULL,
  `type_id` int(11) DEFAULT NULL COMMENT '商品类型\n',
  `media` varchar(256) DEFAULT NULL,
  `detail` blob COMMENT '商品详情\n',
  `status` int(11) DEFAULT '0',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;
